# Generated by Django 4.2 on 2023-04-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_recipe', models.CharField(max_length=100)),
                ('name_of_author', models.CharField(max_length=50)),
                ('claps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StepsDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipedbmodel')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_of_ingredient', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipedbmodel')),
            ],
        ),
    ]
